#spring:
  #datasource:
  #  url: jdbc:h2:mem:test
  #  driver-class-name: org.h2.Driver
  #  username: sa
  #  password:
  #  intialization-mode: always
  #  schema: classpath:sql/schema.sql
  #  data: classpath:sql/data.sql
  #jpa:
  #  database-platform: org.hibernate.dialect.H2Dialect
  #  hibernate:
  #    ddl-auto: validate
h2:
  console:
  enabled: true
r2dbc:
  url: r2dbc:h2:mem:///testdb
  username: sa
  password:
  intialization-mode: always
