info:
  app:
    encoding: 'UTF-8'
    java:
      source: '11.0.11'
      target: '11.0.11'
logging:
  config: classpath:log4j2-spring-dev.xml
app:
  version: '0.0.1-SNAPSHOT'
  name: 'reactiveapi'
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: 'reactiveapi'
  main:
    banner-mode: 'OFF'
server:
  compression:
    enabled: true
